### PR TITLE
doc:note the required location of the lyrics db repo

### PR DESCRIPTION
**Pull request by andy5995**
I wasn't sure how you'd want this worded but I just gave it my best shot ;)

Also, would you like the new text all on one line? I usually wrap text at around 80 cols in md docs because for me, it's easier to read, edit and review diffs later.

@snshn If you're interested in the submodule idea I mentioned in #48, I can use this PR to do that instead.

### CODE REVIEW

**Comment by snshn** [comment]
Thank you for the PR Andy! I'll go ahead and make it configurable the best way I can. I tried git submodules eons ago when the project just got started, it was a real pain partially since git never got that one feature to be friendly enough.

**Comment by andy5995** [comment]
Yeah, submodules can be a pain.

**Comment by andy5995** [comment]
Any plans to enable [GitHub Discussions](https://docs.github.com/en/free-pro-team@latest/discussions/quickstart#:~:text=GitHub%20Discussions%20is%20a%20collaborative%20communication%20forum%20for,enable%20fluid%2C%20open%20conversation%20in%20a%20public%20forum.) for your repo?

**Comment by snshn** [comment]
Didn't know about Discussions, seems like a new GitHub feature, thank you for the suggestion... do you think it's better to have it for lyrics.git, for lyrics-website-generator.git, or both?

**Comment by andy5995** [comment]
> Didn't know about Discussions, seems like a new GitHub feature, thank you for the suggestion... do you think it's better to have it for lyrics.git, for lyrics-website-generator.git, or both?

I think lyrics.git, the most active repo, to start with. Then decide later if it's needed on the other.

**Comment by snshn** [comment]
It is done, thank you for the suggestion!

**Pull request closed without merging**
